"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

version_string = "1.0"

plist = dict(CFBundleShortVersionString=version_string,
             CFBundleIconFile='Icon.icns',
             CFBundleGetInfoString='PebMessage server v%s' % version_string,
             CFBundleIdentifier='com.ganglion.pebmessage',
             CFBundleName='PebMessage Server',
             CFBundleVersion=version_string,
             NSUIElement=1
             )

APP = ['main.py']
PKGS = ['serial']
DATA_FILES = ["English.lproj", "tray.png", "Icon.icns"]
OPTIONS = {'argv_emulation': True, 'plist': plist}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
